[package]
name = "example-hello-world"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
axum = { path = "../../axum" }
tokio = { version = "1.0", features = ["full"] }

axum-extra = { path = "../../axum-extra", features = ["typed-routing"] }
serde = { version = "1.0", features = ["derive"] }
